"use server";
import {redirect} from "next/navigation";import {dealCheckInputSchema} from "@/features/dealcheck/contracts";import {analyseDealCheck,DealCheckAnalysisError} from "@/features/dealcheck/analyse";import {VercelAiGateway} from "@/features/ai/gateway";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";import {DEALCHECK_PACKS,dealCheckPackKeySchema} from "@/features/dealcheck/catalog";import {getStripe} from "@/lib/stripe/server";import {trustedRequestOrigin} from "@/lib/request-origin";

async function authenticated(){const supabase=await createClient();const {data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")return null;return{supabase,userId};}
export async function runDealCheck(payload:unknown){
 const auth=await authenticated();if(!auth)return{ok:false as const,code:"AUTH_REQUIRED",message:"Sign in to run your DealCheck."};const parsed=dealCheckInputSchema.safeParse(payload);if(!parsed.success)return{ok:false as const,code:"INVALID_INPUT",message:parsed.error.issues[0]?.message??"Check the form and try again."};
 const input=parsed.data;const {data:start,error:startError}=await auth.supabase.rpc("dealcheck_start_check",{p_client_request_id:input.clientRequestId,p_raw_offer:input.rawOffer,p_platform:input.platform,p_followers:input.followers,p_average_views:input.averageViews,p_engagement_rate:input.engagementRate});
 if(startError){if(startError.message.includes("NO_CREDITS"))return{ok:false as const,code:"NO_CREDITS",message:"You need another DealCheck credit to continue."};return{ok:false as const,code:"START_FAILED",message:"We couldn't start this check. Please try again."};}
 const started=start as {check_id:string;status:string;reused:boolean};if(started.reused)return started.status==="completed"?{ok:true as const,checkId:started.check_id}:{ok:false as const,code:"PROCESSING",message:"This DealCheck is already processing."};
 const admin=createAdminClient();try{const analysis=await analyseDealCheck(input,new VercelAiGateway(),auth.userId);const {error}=await admin.rpc("complete_dealcheck",{p_check_id:started.check_id,p_extracted_data:analysis.extracted,p_valuation_data:analysis.valuation,p_score:analysis.score,p_result:analysis.result,p_ai_usage:analysis.aiUsage});if(error)throw error;return{ok:true as const,checkId:started.check_id};}
 catch(error){const known=error instanceof DealCheckAnalysisError;await admin.rpc("refund_failed_dealcheck",{p_check_id:started.check_id,p_failure_code:known?error.code:"SYSTEM_FAILURE"});return{ok:false as const,code:known?error.code:"SYSTEM_FAILURE",message:known?error.userMessage:"DealCheck couldn't finish this analysis. Your credit has been restored; please try again."};}
}
export async function startDealCheckCheckout(formData:FormData){
 const key=dealCheckPackKeySchema.parse(formData.get("packKey"));const pack=DEALCHECK_PACKS[key];const auth=await authenticated();if(!auth)redirect("/dealcheck/sign-in");await auth.supabase.rpc("dealcheck_initialize_account");
 const origin=await trustedRequestOrigin();const session=await getStripe().checkout.sessions.create({mode:"payment",managed_payments:{enabled:false},line_items:[{price_data:{currency:"gbp",unit_amount:pack.amountMinor,product_data:{name:pack.label,description:"DealCheck credits by Rep Bureau"}},quantity:1}],success_url:`${origin}/dealcheck?billing=processing`,cancel_url:`${origin}/dealcheck?billing=canceled`,client_reference_id:auth.userId,metadata:{kind:"dealcheck_credit_pack",user_id:auth.userId,pack_key:key,credit_quantity:String(pack.credits)}});if(!session.url)throw new Error("Stripe Checkout did not return a URL");redirect(session.url);
}
export async function signOutDealCheck(){const auth=await authenticated();if(auth)await auth.supabase.auth.signOut();redirect("/dealcheck");}
