"use client";
import {useEffect,useState,useTransition} from "react";import {useRouter} from "next/navigation";import {dealCheckInputSchema} from "@/features/dealcheck/contracts";import {runDealCheck} from "./actions";
export const PENDING_DEALCHECK_KEY="repbureau:dealcheck:pending:v1";
const blank=()=>({clientRequestId:crypto.randomUUID(),rawOffer:"",platform:"tiktok",followers:"",averageViews:"",engagementRate:""});
export function DealCheckForm({signedIn}:{signedIn:boolean}){const router=useRouter();const [form,setForm]=useState(blank);const [error,setError]=useState("");const [pending,startTransition]=useTransition();
 useEffect(()=>{const saved=sessionStorage.getItem(PENDING_DEALCHECK_KEY);if(!saved)return;try{const parsed=dealCheckInputSchema.safeParse(JSON.parse(saved));if(parsed.success)queueMicrotask(()=>setForm({...parsed.data,followers:String(parsed.data.followers),averageViews:parsed.data.averageViews===null?"":String(parsed.data.averageViews),engagementRate:parsed.data.engagementRate===null?"":String(parsed.data.engagementRate)}));}catch{/* Ignore corrupt browser-local draft. */}},[]);
 const field=(name:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(current=>({...current,[name]:event.target.value}));
 function submit(event:React.FormEvent){event.preventDefault();setError("");const parsed=dealCheckInputSchema.safeParse(form);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Check the form.");return;}sessionStorage.setItem(PENDING_DEALCHECK_KEY,JSON.stringify(parsed.data));if(!signedIn){router.push("/dealcheck/sign-in");return;}startTransition(async()=>{const result=await runDealCheck(parsed.data);if(result.ok){sessionStorage.removeItem(PENDING_DEALCHECK_KEY);router.push(`/dealcheck/check/${result.checkId}`);}else{const retry={...parsed.data,clientRequestId:crypto.randomUUID()};sessionStorage.setItem(PENDING_DEALCHECK_KEY,JSON.stringify(retry));setForm(current=>({...current,clientRequestId:retry.clientRequestId}));setError(result.code==="NO_CREDITS"?`${result.message} Choose a credit pack in Pricing below.`:result.message);}});}
 return <form className="dealcheck-form" onSubmit={submit} noValidate><label className="dealcheck-offer">Paste the brand offer<textarea name="rawOffer" value={form.rawOffer} onChange={field("rawOffer")} maxLength={12000} required placeholder="Paste the email or message from the brand…"/><small>{String(form.rawOffer).length.toLocaleString("en-GB")} / 12,000</small></label><div className="dealcheck-fields"><label>Platform<select name="platform" value={form.platform} onChange={field("platform")}><option value="tiktok">TikTok</option><option value="instagram">Instagram</option></select></label><label>Followers<input name="followers" inputMode="numeric" min="1000" max="999999" value={form.followers??""} onChange={field("followers")} required placeholder="25,000"/></label><label>Average views <span>Optional</span><input name="averageViews" inputMode="numeric" min="0" value={form.averageViews??""} onChange={field("averageViews")} placeholder="18,000"/><small>Improves the estimate</small></label><label>Engagement rate <span>Optional</span><div className="dealcheck-suffix"><input name="engagementRate" inputMode="decimal" min="0" max="100" value={form.engagementRate??""} onChange={field("engagementRate")} placeholder="4.2"/><b>%</b></div></label></div>{error?<p className="dealcheck-error" role="alert">{error}</p>:null}<div className="dealcheck-submit"><button className="dealcheck-button" disabled={pending}>{pending?"Checking your deal…":"Check my deal"}</button><p>Your first DealCheck is free. No card required.</p></div><p className="sr-only" aria-live="polite">{pending?"Your DealCheck is being prepared.":""}</p></form>;
}
