import type {Metadata} from "next";import Link from "next/link";import {hasSupabaseConfig} from "@/lib/env";import {createClient} from "@/lib/supabase/server";import {legalPublicationConfig} from "@/lib/env.server";import {DealCheckForm} from "./DealCheckForm";import {CreditPacks} from "./CreditPacks";import {signOutDealCheck} from "./actions";
export const metadata:Metadata={title:"DealCheck by Rep Bureau — Know what the deal is worth",description:"Check a UK TikTok or Instagram brand offer, including fee, usage rights, exclusivity and a recommended counter."};
export const dynamic="force-dynamic";
export default async function DealCheckPage({searchParams}:{searchParams:Promise<{billing?:string}>}){let userId:string|undefined;let balance:number|undefined;if(hasSupabaseConfig()){const supabase=await createClient();const {data}=await supabase.auth.getClaims();userId=typeof data?.claims?.sub==="string"?data.claims.sub:undefined;if(userId){const {data:credit}=await supabase.rpc("dealcheck_initialize_account");balance=typeof credit==="number"?credit:undefined;}}const {billing}=await searchParams;const legal=legalPublicationConfig();return <main className="dealcheck-shell"><header className="dealcheck-header"><Link className="dealcheck-wordmark" href="/dealcheck">REP BUREAU <i>/</i> DEALCHECK</Link><nav>{userId?<><Link href="/dealcheck/checks">My checks</Link><span>{balance??0} credit{balance===1?"":"s"}</span><form action={signOutDealCheck}><button>Sign out</button></form></>:<Link href="/dealcheck/sign-in">Sign in</Link>}</nav></header>{billing==="processing"?<p className="dealcheck-notice" role="status">Payment received. Stripe is confirming your credits; refresh shortly.</p>:null}
<section className="dealcheck-hero"><div><p className="dealcheck-kicker">DEALCHECK BY REP BUREAU</p><h1>Know what the deal is really worth.</h1><p className="dealcheck-lede">Paste the brand offer. DealCheck checks the fee, usage rights, exclusivity and hidden value before you say yes.</p></div><DealCheckForm signedIn={Boolean(userId)}/></section>
<section className="dealcheck-four" aria-label="What DealCheck checks">{[["01","Fee","See the offer against a clear UK short-form range."],["02","Usage rights","Price paid use, whitelisting and open-ended rights."],["03","Exclusivity & terms","Spot the restrictions and scope hiding in the brief."],["04","Your counter","Leave with a number and a reply you can send."]].map(([n,h,p])=><article key={n}><span>{n}</span><h2>{h}</h2><p>{p}</p></article>)}</section>
<section className="dealcheck-example"><p className="dealcheck-kicker">ILLUSTRATIVE EXAMPLE</p><div><h2>A £400 offer can carry £1,000+ of scope.</h2><p>One sponsored video, three months&apos; paid usage and category exclusivity. DealCheck separates the content fee from the rights before calculating a directional range.</p></div><dl><div><dt>Brand offer</dt><dd>£400</dd></div><div><dt>Illustrative range</dt><dd>£800–£1,400</dd></div><div><dt>Terms spotted</dt><dd>Paid usage · Exclusivity</dd></div></dl></section>
<section className="dealcheck-how"><p className="dealcheck-kicker">HOW IT WORKS</p><ol><li><b>Paste</b><span>Add the offer and your creator metrics.</span></li><li><b>Check</b><span>DealCheck extracts the scope and prices it consistently.</span></li><li><b>Reply</b><span>Use the recommended counter and ready-to-copy wording.</span></li></ol></section>
<section className="dealcheck-pricing" id="pricing"><div><p className="dealcheck-kicker">SIMPLE PRICING</p><h2>One free check. Then buy only what you need.</h2><p>No subscription. Credits do not expire in V1.</p></div><CreditPacks/></section>
<section className="dealcheck-faq"><p className="dealcheck-kicker">FAQ</p><details><summary>Is this a guaranteed market price?</summary><p>No. It is directional negotiation guidance based on the stated scope and conservative UK benchmarks.</p></details><details><summary>What deals can I check?</summary><p>UK TikTok sponsored videos and Instagram Reels for creators with 1,000–999,999 followers, paid in GBP.</p></details><details><summary>Is DealCheck legal advice?</summary><p>No. It highlights commercial terms, but it does not replace a lawyer for contract advice.</p></details></section>
<footer className="dealcheck-footer"><span>DEALCHECK BY REP BUREAU</span><p>A clearer second opinion before you reply.</p>{legal?<nav><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav>:null}</footer></main>}
