import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/replio/AppShell";
import { requireUser } from "@/features/auth/require-user";
import { dealState, dealStates } from "@/features/deals/state";
import { commercialExtractorOutput, pricingOutput, replyOutput, riskOutput, strategyOutput } from "@/features/ai/contracts";
import { AnalysisAutoRefresh } from "@/features/ai/AnalysisAutoRefresh";
import { ReplyComposer } from "@/features/deals/ReplyComposer";
import { serverEnv } from "@/lib/env.server";
import { addDealNote, completeDealOutcome, confirmInvoicePaid, finaliseInvoice, generateInvoicePdf, prepareInvoice, recycleDeal, requestDealAnalysis, saveOperationalFact, updateDealState } from "../actions";

export default async function DealWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase } = await requireUser();
  const { data: deal } = await supabase.from("deals").select("id,title,status,operational_stage,currency,current_offer_minor,final_agreed_minor,primary_platform,brand_id,created_at").eq("id", id).is("deleted_at", null).maybeSingle();
  if (!deal) notFound();
  const [{ data: threads }, { data: offers }, { data: terms }, { data: deliverables }, { data: notes }, { data: activity }, { data: snapshot },{data:operationalFacts},{data:deadlines},{data:contract},{data:invoice}] = await Promise.all([
    supabase.from("deal_threads").select("id").eq("deal_id", id),
    supabase.from("deal_offers").select("id,offered_by,amount_minor,currency,offer_type,observed_at").eq("deal_id", id).order("observed_at", { ascending: false }),
    supabase.from("deal_terms").select("id,term_type,display_value,fact_state").eq("deal_id", id).eq("is_current", true),
    supabase.from("deal_deliverables").select("id,platform,deliverable_type,quantity,due_at,status").eq("deal_id", id),
    supabase.from("deal_notes").select("id,body,created_at").eq("deal_id", id).order("created_at", { ascending: false }),
    supabase.from("activity_events").select("id,event_type,metadata,created_at").eq("entity_type", "deal").eq("entity_id", id).order("created_at", { ascending: false }),
    supabase.from("analysis_snapshots").select("id,state,structured_output,created_at,completed_at,failure_class").eq("deal_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),
    supabase.from("deal_operational_facts").select("id,field_key,display_value,source_kind,created_at").eq("deal_id",id).eq("is_current",true).order("field_key"),
    supabase.from("deal_deadlines").select("id,label,deadline_type,due_at,status").eq("deal_id",id).neq("status","cancelled").order("due_at"),
    supabase.from("deal_contract_references").select("received_status,signature_status,reference").eq("deal_id",id).maybeSingle(),
    supabase.from("invoices").select("id,status,invoice_number,currency,subtotal_minor,tax_minor,total_minor,issue_date,due_date,billing_entity,billing_address,accounts_payable_email,purchase_order,creator_reviewed_at,sent_at,paid_confirmed_at,invoice_line_items(id,position,description,quantity,unit_amount_minor,line_total_minor)").eq("deal_id",id).not("status","in","(void,written_off)").maybeSingle(),
  ]);
  const threadIds = (threads ?? []).map((thread) => thread.id);
  const { data: messages } = threadIds.length ? await supabase.from("gmail_messages").select("id,direction,from_address,to_addresses,subject,body_text,internal_date").in("deal_thread_id", threadIds).order("internal_date") : { data: [] };
  const messageIds = (messages ?? []).map((message) => message.id);
  const { data: attachments } = messageIds.length ? await supabase.from("gmail_attachment_references").select("id,gmail_message_id,filename,mime_type,size_bytes").in("gmail_message_id", messageIds) : { data: [] };
  const state = dealState(deal.status);
  const output=(snapshot?.structured_output??{}) as Record<string,unknown>;
  const { data: workerRuns } = snapshot ? await supabase.from("ai_worker_runs").select("worker_name,state,estimated_cost_microunits").eq("snapshot_id",snapshot.id).order("started_at") : { data: [] };
  const [{data:analysisScore},{data:replyDraft},{data:dealOutcome}]=await Promise.all([
    snapshot?supabase.from("analysis_scores").select("score,components,improvement_actions").eq("snapshot_id",snapshot.id).maybeSingle():Promise.resolve({data:null}),
    supabase.from("reply_drafts").select("subject,body,version,state,respectful_challenge,challenge_acknowledged_at").eq("deal_id",deal.id).maybeSingle(),
    supabase.from("deal_outcomes").select("outcome,currency,initial_offer_minor,final_amount_minor,estimated_additional_earnings_minor,uplift_percent,negotiation_rounds,major_term_improvements,eae_method_version").eq("deal_id",deal.id).maybeSingle(),
  ]);
  const {data:invoiceVersion}=invoice?await supabase.from("invoice_versions").select("version,pdf_storage_path,pdf_sha256").eq("invoice_id",invoice.id).order("version",{ascending:false}).limit(1).maybeSingle():{data:null};
  const analysisActive=snapshot?.state === "queued" || snapshot?.state === "running" || snapshot?.state === "partial";
  const estimatedCost=(workerRuns??[]).reduce((total,run)=>total+(run.estimated_cost_microunits??0),0)/1_000_000;
  const extraction=commercialExtractorOutput.safeParse(output.commercial_extractor);
  const pricing=pricingOutput.safeParse(output.pricing_engine); const risks=riskOutput.safeParse(output.risk_engine); const strategy=strategyOutput.safeParse(output.strategy_engine); const reply=replyOutput.safeParse(output.reply_engine);
  return <AppShell>
    <AnalysisAutoRefresh active={analysisActive}/>
    <header className="page-header deal-heading"><div><Link className="back-link" href="/deals">← Deals</Link><h1>{deal.title}</h1><p className="status-explainer"><span className={`status-pill status-${deal.status}`}>{state.label}</span> {state.detail}</p></div><form action={recycleDeal}><input type="hidden" name="dealId" value={deal.id}/><input type="hidden" name="recycled" value="true"/><button className="button button-secondary">Move to recycle bin</button></form></header>
    <div className="workspace-grid">
      <section className="workspace-analysis" aria-label="Commercial details">
        <section className="workspace-card analysis-card"><div className="section-heading"><div><p className="eyebrow">Replio analysis</p><h2>{snapshot ? snapshot.state === "completed" ? "Analysis ready" : snapshot.state === "failed" ? "Analysis paused" : "Analysis in progress" : "Analyse this deal"}</h2></div>{snapshot && <span className={`status-pill analysis-${snapshot.state}`}>{snapshot.state}</span>}</div>
          {!snapshot && <p className="muted">Five focused workers will extract the offer, assess pricing and risk, recommend a strategy, and prepare an editable reply. Your conversation remains available if analysis fails.</p>}
          {snapshot?.state === "failed" && <p className="error-text">Analysis could not complete. You can retry without losing the Deal or conversation.</p>}
          {(!snapshot || snapshot.state === "failed") && <form action={requestDealAnalysis}><input type="hidden" name="dealId" value={deal.id}/><button className="button button-primary" disabled={!serverEnv.AI_GATEWAY_MODEL}>{serverEnv.AI_GATEWAY_MODEL ? snapshot ? "Retry analysis" : "Analyse deal" : "AI activation pending"}</button></form>}
          {pricing.success && <div className="recommendation-grid"><div><span>Ideal ask</span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:pricing.data.currency}).format(pricing.data.ideal_ask_minor/100)}</strong></div><div><span>Expected</span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:pricing.data.currency}).format(pricing.data.expected_settlement_minor/100)}</strong></div><div><span>Minimum worthwhile</span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:pricing.data.currency}).format(pricing.data.minimum_worthwhile_minor/100)}</strong></div></div>}
          {analysisScore && <div className="score-panel"><div><span>Replio Score</span><strong>{analysisScore.score}</strong><small>/ 100</small></div><section><h3>What would improve this?</h3><ul>{(analysisScore.improvement_actions as string[]).map((action)=><li key={action}>{action}</li>)}</ul></section></div>}
          {extraction.success && extraction.data.missing_material_terms.length>0 && <p className="analysis-caveat"><strong>Needs clarification:</strong> {extraction.data.missing_material_terms.join(", ")}</p>}
          {extraction.success && <details className="evidence-panel"><summary>Why? View source evidence</summary><ul>{[...extraction.data.offers,...extraction.data.deliverables,...extraction.data.terms].flatMap((fact)=>fact.evidence).map((item,index)=><li key={`${item.message_id}-${index}`}><a href={`#message-${item.message_id}`}>{item.excerpt}</a><small>{item.locator}</small></li>)}</ul></details>}
          {risks.success && <ul className="risk-list">{risks.data.risks.map((risk,index)=><li key={`${risk.category}-${index}`}><strong>{risk.summary}</strong><span>{risk.severity} priority</span></li>)}</ul>}
          {strategy.success && <div><h3>Negotiation approach</h3><p>{strategy.data.primary_objective}</p><ol>{strategy.data.sequence.map((step,index)=><li key={index}>{step}</li>)}</ol></div>}
          {reply.success && <div><h3>Suggested reply</h3><div className="draft-preview"><strong>{reply.data.subject}</strong><p>{reply.data.body}</p></div></div>}
          {!!workerRuns?.length && <div><h3>Worker progress</h3><ul className="fact-list">{workerRuns.map((run)=><li key={run.worker_name}><span>{run.worker_name.replaceAll("_"," ")}</span><strong>{run.state}</strong></li>)}</ul><p className="muted">Estimated analysis cost so far: ${estimatedCost.toFixed(4)}</p></div>}
        </section>
        <section className="workspace-card"><div className="section-heading"><div><p className="eyebrow">Next move</p><h2>Deal state</h2></div><span className="status-pill">{deal.operational_stage.replaceAll("_"," ")}</span></div><form action={updateDealState} className="state-form"><input type="hidden" name="dealId" value={deal.id}/><select name="status" defaultValue={deal.status} aria-label="Deal state">{Object.entries(dealStates).map(([value, copy]) => <option value={value} key={value}>{copy.label}</option>)}</select><button className="button button-primary">Update state</button></form></section>
        <section className="workspace-card"><p className="eyebrow">Living Deal record</p><h2>Commercial & admin facts</h2><p className="muted">Rep Bureau reuses facts from the conversation and your profile. Your edits are kept as history and always outrank imported values.</p>{operationalFacts?.length?<dl className="detail-grid">{operationalFacts.map(fact=><div key={fact.id}><dt>{fact.field_key.replaceAll("_"," ")}</dt><dd>{fact.display_value}</dd><small>{fact.source_kind.replaceAll("_"," ")}</small></div>)}</dl>:<p className="muted">No additional admin facts have been confirmed yet.</p>}<details className="evidence-panel"><summary>Add or correct a fact</summary><form action={saveOperationalFact} className="outcome-form"><input type="hidden" name="dealId" value={deal.id}/><label>Field<select name="fieldKey"><option value="brand_name">Brand name</option><option value="agency_name">Agency name</option><option value="contact_name">Contact name</option><option value="contact_email">Contact email</option><option value="billing_entity">Billing entity</option><option value="billing_address">Billing address</option><option value="accounts_payable_email">Accounts payable email</option><option value="purchase_order">Purchase order</option><option value="invoice_instructions">Invoice instructions</option><option value="campaign_start">Campaign start</option><option value="campaign_end">Campaign end</option><option value="usage_terms">Usage terms</option><option value="exclusivity_terms">Exclusivity terms</option><option value="paid_media_terms">Paid media terms</option></select></label><label>Confirmed value<textarea name="displayValue" required maxLength={5000}/></label><button className="button button-primary">Save confirmed fact</button></form></details>{deadlines?.length?<><h3>Deadlines</h3><ul className="fact-list">{deadlines.map(deadline=><li key={deadline.id}><span>{deadline.label}</span><strong>{new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(deadline.due_at))}</strong></li>)}</ul></>:null}{contract?<p className="muted">Contract: {contract.received_status.replaceAll("_"," ")} · {contract.signature_status.replaceAll("_"," ")}{contract.reference?` · ${contract.reference}`:""}</p>:null}</section>
        <section className="workspace-card"><p className="eyebrow">Invoice & payment</p><h2>{invoice?.invoice_number??(invoice?"Draft invoice":"Invoice admin")}</h2>{invoice?<><dl className="detail-grid"><div><dt>Status</dt><dd>{invoice.status.replaceAll("_"," ")}</dd></div><div><dt>Total</dt><dd>{new Intl.NumberFormat("en-GB",{style:"currency",currency:invoice.currency}).format(invoice.total_minor/100)}</dd></div><div><dt>Bill to</dt><dd>{invoice.billing_entity??"Needs review"}</dd></div><div><dt>Due</dt><dd>{invoice.due_date?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(invoice.due_date)):"Set when finalised"}</dd></div></dl><h3>Line items</h3><ul className="fact-list">{invoice.invoice_line_items.map(item=><li key={item.id}><span>{item.description} × {item.quantity}</span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:invoice.currency}).format(item.line_total_minor/100)}</strong></li>)}</ul>{invoice.status==="draft"?<form action={finaliseInvoice}><input type="hidden" name="dealId" value={deal.id}/><input type="hidden" name="invoiceId" value={invoice.id}/><input type="hidden" name="expectedTotal" value={invoice.total_minor}/><label className="consent"><input required type="checkbox"/> I have reviewed the invoice facts and total.</label><button className="button button-primary">Finalise, number & generate PDF</button></form>:null}{["sent","query"].includes(invoice.status)?<form action={confirmInvoicePaid}><input type="hidden" name="dealId" value={deal.id}/><input type="hidden" name="invoiceId" value={invoice.id}/><label className="consent"><input required type="checkbox" name="confirmation" value="confirmed"/> I confirm this payment has been received.</label><button className="button button-primary">Mark paid</button></form>:null}{invoice.status==="ready"?<div className="notice">{invoiceVersion?.pdf_storage_path?<><p>Version {invoiceVersion.version} PDF is ready. Nothing has been sent.</p><a className="button button-secondary" href={`/api/invoices/${invoice.id}/pdf`}>Download invoice PDF</a></>:<form action={generateInvoicePdf}><input type="hidden" name="dealId" value={deal.id}/><input type="hidden" name="invoiceId" value={invoice.id}/><p>The numbered invoice needs its private PDF regenerated.</p><button className="button button-secondary">Generate PDF</button></form>}</div>:null}</>:<><p className="muted">Rep Bureau can prepare an invoice from the agreed fee, Deal facts and your saved issuer profile.</p><form action={prepareInvoice}><input type="hidden" name="dealId" value={deal.id}/><button className="button button-primary" disabled={deal.final_agreed_minor===null}>Prepare invoice</button></form>{deal.final_agreed_minor===null?<p className="muted">Record a final agreed fee first.</p>:null}</>}</section>
        <section className="workspace-card"><p className="eyebrow">Private commercial learning</p><h2>{dealOutcome?"Outcome recap":"Complete this Deal"}</h2>{dealOutcome?<><dl className="detail-grid"><div><dt>Outcome</dt><dd>{dealOutcome.outcome}</dd></div><div><dt>Final amount</dt><dd>{new Intl.NumberFormat("en-GB",{style:"currency",currency:dealOutcome.currency}).format((dealOutcome.final_amount_minor??0)/100)}</dd></div><div><dt>Estimated additional earnings</dt><dd>{new Intl.NumberFormat("en-GB",{style:"currency",currency:dealOutcome.currency}).format(dealOutcome.estimated_additional_earnings_minor/100)}</dd></div><div><dt>Negotiation rounds</dt><dd>{dealOutcome.negotiation_rounds??"Not recorded"}</dd></div></dl><details className="evidence-panel"><summary>How we estimated this</summary><p>Positive uplift from the initial brand offer to the final agreed amount. Negative uplift is always counted as zero. Method version {dealOutcome.eae_method_version}.</p></details></>:<form action={completeDealOutcome} className="outcome-form"><input type="hidden" name="dealId" value={deal.id}/><label>Outcome<select name="outcome" defaultValue="success"><option value="success">Successful agreement</option><option value="declined">Declined</option><option value="lost">Lost</option></select></label><label>Final amount ({deal.currency})<input name="finalAmount" inputMode="decimal" pattern="\d+(\.\d{1,2})?" required placeholder="1250.00"/></label><label>Negotiation rounds<input name="rounds" type="number" min="0" max="100" defaultValue="0" required/></label><label>Major term improvements<textarea name="improvements" maxLength={5000} placeholder="One improvement per line"/></label><label>What should Replio learn for you?<textarea name="learning" maxLength={5000}/></label><p className="muted">Your recap stays private. Replio contributes only unlinkable structured dimensions to benchmarks, never your identity, messages, contacts or notes.</p><button className="button button-primary">Save outcome</button></form>}</section>
        <section className="workspace-card"><h2>Commercial snapshot</h2><dl className="detail-grid"><div><dt>Current offer</dt><dd>{deal.current_offer_minor === null ? "Not recorded" : new Intl.NumberFormat("en-GB", { style: "currency", currency: deal.currency }).format(deal.current_offer_minor / 100)}</dd></div><div><dt>Platform</dt><dd>{deal.primary_platform ?? "Not confirmed"}</dd></div></dl>
          <h3>Offer history</h3>{offers?.length ? <ul className="fact-list">{offers.map((offer) => <li key={offer.id}><span>{offer.offered_by === "brand" ? "Brand" : "You"} · {offer.offer_type}</span><strong>{new Intl.NumberFormat("en-GB", { style: "currency", currency: offer.currency }).format(offer.amount_minor / 100)}</strong></li>)}</ul> : <p className="muted">No structured offers recorded yet.</p>}
          <h3>Terms</h3>{terms?.length ? <ul className="fact-list">{terms.map((term) => <li key={term.id}><span>{term.term_type.replaceAll("_", " ")}</span><strong>{term.display_value}</strong></li>)}</ul> : <p className="muted">No commercial terms recorded yet.</p>}
          <h3>Deliverables</h3>{deliverables?.length ? <ul className="fact-list">{deliverables.map((item) => <li key={item.id}><span>{item.quantity} × {item.deliverable_type}</span><strong>{item.status.replaceAll("_", " ")}</strong></li>)}</ul> : <p className="muted">No deliverables recorded yet.</p>}
        </section>
        <section className="workspace-card"><h2>Private notes</h2><form action={addDealNote} className="note-form"><input type="hidden" name="dealId" value={deal.id}/><textarea name="body" required maxLength={10000} placeholder="Add context only you can see" aria-label="Private note"/><button className="button button-primary">Save note</button></form>{notes?.map((note) => <article className="note" key={note.id}><p>{note.body}</p><time>{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(note.created_at))}</time></article>)}</section>
        <section className="workspace-card"><h2>Activity</h2>{activity?.length ? <ol className="timeline">{activity.map((event) => <li key={event.id}><strong>{event.event_type.replaceAll("_", " ")}</strong><time>{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.created_at))}</time></li>)}</ol> : <p className="muted">Activity will appear as the deal changes.</p>}</section>
      </section>
      <section className="conversation-pane" aria-label="Email conversation"><div className="conversation-heading"><p className="eyebrow">Conversation</p><h2>Email thread</h2></div>{messages?.length ? messages.map((message) => <article id={`message-${message.id}`} className={`message-card message-${message.direction}`} key={message.id}><header><strong>{message.direction === "outbound" ? "You" : message.from_address}</strong><time>{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(message.internal_date))}</time></header>{message.subject && <p className="message-subject">{message.subject}</p>}<p className="message-body">{message.body_text || "No plain-text content."}</p>{attachments?.filter((file) => file.gmail_message_id === message.id).map((file) => <span className="attachment" key={file.id}>📎 {file.filename}</span>)}</article>) : <p className="muted">No messages have synced for this deal yet.</p>}{replyDraft?.state==="draft"?<ReplyComposer draft={{dealId:deal.id,subject:replyDraft.subject,body:replyDraft.body,version:replyDraft.version,challenge:replyDraft.challenge_acknowledged_at?null:replyDraft.respectful_challenge}}/>:replyDraft?<p className="reply-state">{replyDraft.state==="sending"?"Reply queued for secure Gmail delivery…":replyDraft.state==="sent"?"Reply sent from your connected Gmail account.":"Reply delivery paused. Try again after reviewing the draft."}</p>:null}</section>
    </div>
  </AppShell>;
}

