"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireUser } from "@/features/auth/require-user";
import { createAdminClient } from "@/lib/supabase/admin";
const schema=z.object({key:z.enum(["ai_worker_enabled","gmail_send_enabled"]),enabled:z.enum(["true","false"]).transform(v=>v==="true"),expectedVersion:z.coerce.number().int().positive(),idempotencyKey:z.string().uuid(),confirmation:z.string().optional()});
export async function setWorkerControl(formData:FormData){const v=schema.parse({key:formData.get("key"),enabled:formData.get("enabled"),expectedVersion:formData.get("expectedVersion"),idempotencyKey:formData.get("idempotencyKey"),confirmation:formData.get("confirmation")});const confirmed=v.confirmation==="confirmed";if(v.enabled&&!confirmed)throw new Error("Confirm that you intend to resume this worker.");const {userId}=await requireUser();const {error}=await createAdminClient().rpc("founder_set_worker_control",{p_founder_user_id:userId,p_key:v.key,p_enabled:v.enabled,p_expected_version:v.expectedVersion,p_confirmation:confirmed,p_idempotency_key:v.idempotencyKey});if(error)throw new Error("The worker control was not changed. Refresh and try again.");revalidatePath("/founder");}
export async function startSupportSession(formData:FormData){const grantId=z.string().uuid().parse(formData.get("grantId"));const idempotencyKey=z.string().uuid().parse(formData.get("idempotencyKey"));const confirmed=formData.get("confirmation")==="confirmed";if(!confirmed)throw new Error("Confirm this private support session.");const {userId}=await requireUser();const {error}=await createAdminClient().rpc("founder_start_support_session",{p_founder_user_id:userId,p_grant_id:grantId,p_confirmation:true,p_idempotency_key:idempotencyKey});if(error)throw new Error("The support session was not started.");revalidatePath("/founder");}
export async function endSupportSession(formData:FormData){const sessionId=z.string().uuid().parse(formData.get("sessionId"));const idempotencyKey=z.string().uuid().parse(formData.get("idempotencyKey"));const {userId}=await requireUser();const {error}=await createAdminClient().rpc("founder_end_support_session",{p_founder_user_id:userId,p_session_id:sessionId,p_idempotency_key:idempotencyKey});if(error)throw new Error("The support session was not ended.");revalidatePath("/founder");}
export async function retryGmailSync(formData:FormData){const eventId=z.string().uuid().parse(formData.get("eventId"));const idempotencyKey=z.string().uuid().parse(formData.get("idempotencyKey"));const {userId}=await requireUser();const {error}=await createAdminClient().rpc("founder_retry_gmail_sync",{p_founder_user_id:userId,p_event_id:eventId,p_idempotency_key:idempotencyKey});if(error)throw new Error("This Gmail sync is not safe to retry. Reauthorization may be required.");revalidatePath("/founder");}
export async function acknowledgeIncident(formData:FormData){const incidentId=z.string().uuid().parse(formData.get("incidentId"));const idempotencyKey=z.string().uuid().parse(formData.get("idempotencyKey"));const {userId}=await requireUser();const {error}=await createAdminClient().rpc("founder_acknowledge_incident",{p_founder_user_id:userId,p_incident_id:incidentId,p_idempotency_key:idempotencyKey});if(error)throw new Error("The incident was not acknowledged.");revalidatePath("/founder");}

