import Link from "next/link";
import {AppShell} from "@/components/replio/AppShell";
import {requireUser} from "@/features/auth/require-user";

export default async function InsightsPage(){
  const {supabase}=await requireUser();const {data:outcomes}=await supabase.from("deal_outcomes").select("id,deal_id,outcome,currency,final_amount_minor,estimated_additional_earnings_minor,uplift_percent,negotiation_rounds,created_at,deals(title)").order("created_at",{ascending:false});
  const totals=new Map<string,{eae:number;final:number;count:number}>();for(const item of outcomes??[]){const value=totals.get(item.currency)??{eae:0,final:0,count:0};value.eae+=item.estimated_additional_earnings_minor;value.final+=item.final_amount_minor??0;value.count++;totals.set(item.currency,value);}
  return <AppShell><header className="page-header"><div><p className="eyebrow">Private performance</p><h1>Insights</h1></div></header>{outcomes?.length?<><section className="insight-grid">{[...totals].map(([currency,total])=><article className="workspace-card" key={currency}><span className="muted">Estimated additional earnings · {currency}</span><h2>{new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(total.eae/100)}</h2><p>{total.count} completed {total.count===1?"Deal":"Deals"}. Currencies remain separate unless a versioned FX source is configured.</p></article>)}</section><section className="content-block"><h2>Completed Deal outcomes</h2><div className="deal-list">{outcomes.map((item)=>{const linked=Array.isArray(item.deals)?item.deals[0]:item.deals;return <Link className="deal-row" href={`/deals/${item.deal_id}`} key={item.id}><div><h2>{linked?.title??"Completed Deal"}</h2><p className="muted">{item.outcome} · {item.negotiation_rounds??0} rounds</p></div><div className="deal-row-meta"><span>Estimated uplift</span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:item.currency}).format(item.estimated_additional_earnings_minor/100)}</strong></div></Link>;})}</div></section></>:<section className="content-block"><h2>No completed outcomes yet</h2><p className="muted">Complete a Deal to create your private recap and begin building honest personal trends.</p><Link className="empty-action" href="/deals">View Deals →</Link></section>}</AppShell>;
}
