import Link from "next/link";
import {AppShell} from "@/components/replio/AppShell";
import {requireUser} from "@/features/auth/require-user";
import {calculatePersonalTrends} from "@/features/insights/trends";

export default async function InsightsPage(){
  const {supabase}=await requireUser();const {data:outcomes}=await supabase.from("deal_outcomes").select("id,deal_id,outcome,currency,final_amount_minor,estimated_additional_earnings_minor,uplift_percent,negotiation_rounds,created_at,deals(title)").order("created_at",{ascending:false});
  const trends=calculatePersonalTrends((outcomes??[]).map(item=>({...item,outcome:item.outcome as "success"|"lost"|"declined"})));
  return <AppShell><header className="page-header"><div><p className="eyebrow">Private performance</p><h1>Insights</h1></div></header>{outcomes?.length?<><section className="insight-grid"><article className="workspace-card"><span className="muted">Successful outcomes</span><h2>{trends.successes} of {trends.completed}</h2><p>{trends.successRate?.toFixed(0)}% across your completed Deals.</p></article><article className="workspace-card"><span className="muted">Typical negotiation</span><h2>{trends.medianRounds===null?"Not enough data":`${trends.medianRounds} rounds`}</h2><p>Median rounds across outcomes where a round count was recorded.</p></article>{trends.byCurrency.map(total=><article className="workspace-card" key={total.currency}><span className="muted">Estimated additional earnings · {total.currency}</span><h2>{new Intl.NumberFormat("en-GB",{style:"currency",currency:total.currency}).format(total.eaeMinor/100)}</h2><p>{total.count} completed {total.count===1?"Deal":"Deals"}. Currencies remain separate unless a versioned FX source is configured.</p></article>)}</section><section className="content-block"><h2>Completed Deal outcomes</h2><div className="deal-list">{outcomes.map((item)=>{const linked=Array.isArray(item.deals)?item.deals[0]:item.deals;return <Link className="deal-row" href={`/deals/${item.deal_id}`} key={item.id}><div><h2>{linked?.title??"Completed Deal"}</h2><p className="muted">{item.outcome} · {item.negotiation_rounds??0} rounds</p></div><div className="deal-row-meta"><span>Estimated uplift</span><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:item.currency}).format(item.estimated_additional_earnings_minor/100)}</strong></div></Link>;})}</div></section></>:<section className="content-block"><h2>No completed outcomes yet</h2><p className="muted">Complete a Deal to create your private recap and begin building honest personal trends.</p><Link className="empty-action" href="/deals">View Deals →</Link></section>}</AppShell>;
}
