import { saveDealContract, saveDealDeadline, updateAdminEmailDraft, updateDraftInvoice } from "@/app/deals/actions";

type Deadline={id:string;label:string;deadline_type:string;due_at:string;status:string};
type Contract={received_status:string;signature_status:string;reference:string|null}|null;
type Invoice={id:string;status:string;currency:string;billing_entity:string|null;billing_address:string|null;accounts_payable_email:string|null;purchase_order:string|null;tax_minor:number;payment_terms_days:number;invoice_line_items:Array<{description:string;quantity:number;unit_amount_minor:number}>}|null;
type Draft={id:string;purpose:string;subject:string;body:string;state:string;version:number;to_address:string};

export function CreatorAdminControls({dealId,deadlines,contract,invoice,drafts}:{dealId:string;deadlines:Deadline[];contract:Contract;invoice:Invoice;drafts:Draft[]}){
  return <section className="workspace-card"><p className="eyebrow">Creator review</p><h2>Admin details you control</h2><p className="muted">Add or correct operational details here. Saving never sends an email.</p>
    <details className="evidence-panel"><summary>Add a deadline</summary><form action={saveDealDeadline} className="outcome-form"><input type="hidden" name="dealId" value={dealId}/><input type="hidden" name="deadlineId" value=""/><DeadlineFields/><button className="button button-secondary">Save deadline</button></form></details>
    {deadlines.map(item=><details className="evidence-panel" key={item.id}><summary>{item.label} · {item.status}</summary><form action={saveDealDeadline} className="outcome-form"><input type="hidden" name="dealId" value={dealId}/><input type="hidden" name="deadlineId" value={item.id}/><DeadlineFields item={item}/><button className="button button-secondary">Update deadline</button></form></details>)}
    <details className="evidence-panel"><summary>Contract status</summary><form action={saveDealContract} className="outcome-form"><input type="hidden" name="dealId" value={dealId}/><div className="form-row"><label>Received<select name="receivedStatus" defaultValue={contract?.received_status??"not_received"}><option value="not_received">Not received</option><option value="received">Received</option><option value="not_applicable">Not applicable</option></select></label><label>Signature<select name="signatureStatus" defaultValue={contract?.signature_status??"not_signed"}><option value="not_signed">Not signed</option><option value="creator_signed">Creator signed</option><option value="fully_signed">Fully signed</option><option value="not_applicable">Not applicable</option></select></label></div><label>Reference or filename<input name="reference" maxLength={500} defaultValue={contract?.reference??""}/></label><button className="button button-secondary">Save contract status</button></form></details>
    {invoice?.status==="draft"?<details className="evidence-panel"><summary>Edit draft invoice</summary><form action={updateDraftInvoice} className="outcome-form"><input type="hidden" name="dealId" value={dealId}/><input type="hidden" name="invoiceId" value={invoice.id}/><label>Billing entity<input name="billingEntity" required maxLength={200} defaultValue={invoice.billing_entity??""}/></label><label>Billing address<textarea name="billingAddress" maxLength={2000} defaultValue={invoice.billing_address??""}/></label><label>Accounts payable email<input name="accountsPayableEmail" type="email" required defaultValue={invoice.accounts_payable_email??""}/></label><label>Purchase order<input name="purchaseOrder" maxLength={200} defaultValue={invoice.purchase_order??""}/></label><label>Description<input name="description" required maxLength={500} defaultValue={invoice.invoice_line_items[0]?.description??"Campaign services"}/></label><div className="form-row"><label>Quantity<input name="quantity" inputMode="decimal" pattern="\d+(\.\d{1,3})?" required defaultValue={invoice.invoice_line_items[0]?.quantity??1}/></label><label>Unit amount ({invoice.currency})<input name="unitAmount" inputMode="decimal" pattern="\d+(\.\d{1,2})?" required defaultValue={((invoice.invoice_line_items[0]?.unit_amount_minor??0)/100).toFixed(2)}/></label></div><div className="form-row"><label>Tax amount ({invoice.currency})<input name="taxAmount" inputMode="decimal" pattern="\d+(\.\d{1,2})?" required defaultValue={(invoice.tax_minor/100).toFixed(2)}/></label><label>Payment terms (days)<input name="paymentTermsDays" type="number" min="0" max="180" required defaultValue={invoice.payment_terms_days}/></label></div><p className="muted">Only enter tax you have decided applies. Rep Bureau does not infer tax.</p><button className="button button-secondary">Save invoice changes</button></form></details>:null}
    {drafts.filter(draft=>["draft","failed"].includes(draft.state)).map(draft=><details className="evidence-panel" key={draft.id}><summary>Edit {draft.purpose==="invoice"?"invoice email":"payment reminder"}</summary><form action={updateAdminEmailDraft} className="outcome-form"><input type="hidden" name="dealId" value={dealId}/><input type="hidden" name="draftId" value={draft.id}/><input type="hidden" name="expectedVersion" value={draft.version}/><p className="muted">Recipient: {draft.to_address}</p><label>Subject<input name="subject" required maxLength={998} defaultValue={draft.subject}/></label><label>Message<textarea name="body" required maxLength={100000} defaultValue={draft.body}/></label><button className="button button-secondary">Save wording</button></form></details>)}
  </section>;
}

function DeadlineFields({item}:{item?:Deadline}){return <><label>Type<select name="deadlineType" defaultValue={item?.deadline_type??"other"}><option value="campaign_start">Campaign start</option><option value="campaign_end">Campaign end</option><option value="draft_due">Draft due</option><option value="approval_due">Approval due</option><option value="publish_due">Publish due</option><option value="invoice_due">Invoice due</option><option value="payment_due">Payment due</option><option value="other">Other</option></select></label><label>Label<input name="label" required maxLength={200} defaultValue={item?.label??""}/></label><label>Due<input name="dueAt" type="datetime-local" required defaultValue={item?new Date(item.due_at).toISOString().slice(0,16):""}/></label><label>Status<select name="status" defaultValue={item?.status??"open"}><option value="open">Open</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label></>}

